"""Backtester abstraction and base classes."""

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Literal

import pandas as pd
from pydantic import BaseModel, Field


class BacktestSignal(BaseModel):
    """Signal generated by strategy."""

    timestamp: datetime = Field(..., description="Signal timestamp")
    asset: str = Field(..., description="Asset identifier")
    action: Literal["LONG", "SHORT", "EXIT"] = Field(
        ..., description="Signal action"
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence level 0-1"
    )
    entry_price: float | None = Field(
        default=None, description="Entry price (for LONG/SHORT)"
    )
    exit_price: float | None = Field(default=None, description="Exit price (for EXIT)")
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional signal metadata"
    )


class PortfolioState(BaseModel):
    """Portfolio state at a point in time."""

    timestamp: datetime = Field(..., description="State timestamp")
    positions: dict[str, float] = Field(
        default_factory=dict, description="Asset -> quantity"
    )
    cash: float = Field(..., description="Available cash")
    equity: float = Field(..., description="Total equity")

    @property
    def total_value(self) -> float:
        """Total portfolio value."""
        return self.equity + self.cash


class BacktestMetrics(BaseModel):
    """Final backtest metrics."""

    total_return: float = Field(..., description="Total return %")
    annual_return: float = Field(..., description="Annual return %")
    max_drawdown: float = Field(..., description="Max drawdown %")
    sharpe_ratio: float = Field(..., description="Sharpe ratio")
    profit_factor: float = Field(..., description="Profit factor")
    trade_count: int = Field(..., ge=0, description="Total trades")
    win_rate: float = Field(..., ge=0.0, le=1.0, description="Win rate 0-1")
    equity_curve: list[float] = Field(
        default_factory=list, description="Daily equity values"
    )
    trade_log: list[dict[str, Any]] = Field(
        default_factory=list, description="All trades with entry/exit"
    )


class Backtester(ABC):
    """Abstraction for quantitative strategy backtesting."""

    @abstractmethod
    def setup(self, config: dict[str, Any]) -> None:
        """Initialize backtester with configuration.

        Args:
            config: Configuration dict with strategy parameters.

        Raises:
            ValueError: If config invalid.
        """

    @abstractmethod
    def generate_signals(
        self,
        features: dict[str, pd.DataFrame],
        timestamp: datetime,
    ) -> list[BacktestSignal]:
        """Generate signals based on available features.

        Args:
            features: Dict mapping asset -> feature DataFrame.
            timestamp: Current timestamp (point-in-time).

        Returns:
            List of BacktestSignal.

        Note:
            Must use only data available at timestamp (no look-ahead).
        """

    @abstractmethod
    def on_signal(self, signal: BacktestSignal) -> None:
        """Process signal and update portfolio.

        Args:
            signal: BacktestSignal to process.
        """

    @abstractmethod
    def get_portfolio_state(self) -> PortfolioState:
        """Get current portfolio state.

        Returns:
            PortfolioState snapshot.
        """

    @abstractmethod
    def backtest(
        self,
        start_date: datetime,
        end_date: datetime,
        initial_capital: float,
    ) -> BacktestMetrics:
        """Run full backtest walk-forward.

        Args:
            start_date: Backtest start date.
            end_date: Backtest end date.
            initial_capital: Starting capital in USD.

        Returns:
            BacktestMetrics with results.

        Raises:
            ValueError: If dates or capital invalid.
        """

    @abstractmethod
    def get_metrics(self) -> BacktestMetrics:
        """Get final backtest metrics.

        Returns:
            BacktestMetrics.
        """

    @abstractmethod
    def close(self) -> None:
        """Clean up resources."""
